<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="5" failures="0" skipped="0" tests="5" time="2.211" timestamp="2023-11-22T23:15:00.101243" hostname="80ac3eb7f7f2"><testcase classname="" name="tests.test_helpers" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/pendulum-2.1.2/tests/test_helpers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_helpers.py:7: in &lt;module&gt;
    import pytz
E   ModuleNotFoundError: No module named 'pytz'</error></testcase><testcase classname="" name="tests.test_main" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/pendulum-2.1.2/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_main.py:1: in &lt;module&gt;
    import pytz
E   ModuleNotFoundError: No module named 'pytz'</error></testcase><testcase classname="" name="tests.datetime.test_comparison" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/pendulum-2.1.2/tests/datetime/test_comparison.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/datetime/test_comparison.py:4: in &lt;module&gt;
    import pytz
E   ModuleNotFoundError: No module named 'pytz'</error></testcase><testcase classname="" name="tests.datetime.test_construct" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/pendulum-2.1.2/tests/datetime/test_construct.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/datetime/test_construct.py:6: in &lt;module&gt;
    from freezegun import freeze_time
E   ModuleNotFoundError: No module named 'freezegun'</error></testcase><testcase classname="" name="tests.time.test_sub" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/pendulum-2.1.2/tests/time/test_sub.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/time/test_sub.py:6: in &lt;module&gt;
    import pytz
E   ModuleNotFoundError: No module named 'pytz'</error></testcase></testsuite></testsuites>