<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="6" failures="0" skipped="0" tests="6" time="4.959" timestamp="2023-11-21T05:00:44.783514" hostname="b80581c01e0f"><testcase classname="" name="tests.providers.test_date_time" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/providers/test_date_time.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/providers/test_date_time.py:13: in &lt;module&gt;
    import freezegun
E   ModuleNotFoundError: No module named 'freezegun'</error></testcase><testcase classname="" name="tests.providers.test_internet" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/providers/test_internet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/providers/test_internet.py:10: in &lt;module&gt;
    from validators import domain as validate_domain
E   ModuleNotFoundError: No module named 'validators'</error></testcase><testcase classname="" name="tests.providers.test_ssn" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/providers/test_ssn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/providers/test_ssn.py:10: in &lt;module&gt;
    import freezegun
E   ModuleNotFoundError: No module named 'freezegun'</error></testcase><testcase classname="" name="tests.providers.test_user_agent" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/providers/test_user_agent.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/providers/test_user_agent.py:6: in &lt;module&gt;
    from freezegun import freeze_time
E   ModuleNotFoundError: No module named 'freezegun'</error></testcase><testcase classname="" name="tests.sphinx.test_docstring" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/sphinx/test_docstring.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/sphinx/test_docstring.py:8: in &lt;module&gt;
    from faker.sphinx.docstring import DEFAULT_SAMPLE_SIZE, DEFAULT_SEED, ProviderMethodDocstring, Sample
E   ModuleNotFoundError: No module named 'faker.sphinx'</error></testcase><testcase classname="" name="tests.sphinx.test_validator" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/Faker-15.3.4/tests/sphinx/test_validator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/sphinx/test_validator.py:6: in &lt;module&gt;
    from faker.sphinx.validator import SampleCodeValidator
E   ModuleNotFoundError: No module named 'faker.sphinx'</error></testcase></testsuite></testsuites>