GLOB sdist-make: /workdir/pytest-cov-4.0.0/setup.py
cpythonlibtest-unit-test-tests create: /workdir/pytest-cov-4.0.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rci/requirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/pytest-cov-4.0.0/.tox/.tmp/package/1/pytest-cov-4.0.0.zip
cpythonlibtest-unit-test-tests installed: cachetools==5.3.2,chardet==5.2.0,colorama==0.4.6,coverage==7.3.2,distlib==0.3.7,exceptiongroup==1.2.0,filelock==3.13.1,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,platformdirs==4.0.0,pluggy==1.3.0,pyproject-api==1.6.1,pytest==7.4.3,pytest-cov @ file:///workdir/pytest-cov-4.0.0/.tox/.tmp/package/1/pytest-cov-4.0.0.zip#sha256=0be8eb135329842fe40e73d9aa5cf3caa60bcfabc0eaf38af788217ee9b90c56,six==1.16.0,tomli==2.0.1,tox==4.11.4,virtualenv==20.24.7
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='4151478888'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/pytest-cov/4.0.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/pytest-cov-4.0.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/pytest-cov-4.0.0
configfile: setup.cfg
testpaths: tests
plugins: cov-4.0.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_pytest_cov.py ___________________
ImportError while importing test module '/workdir/pytest-cov-4.0.0/tests/test_pytest_cov.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pytest_cov.py:14: in <module>
    import xdist
E   ModuleNotFoundError: No module named 'xdist'
=============================== warnings summary ===============================
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1316
  /workdir/pytest-cov-4.0.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1316: PytestRemovedIn8Warning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /workdir/results/pytest-cov/4.0.0/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_pytest_cov.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.22s ==========================
ERROR: InvocationError for command /workdir/pytest-cov-4.0.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/pytest-cov/4.0.0/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
