<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="29" failures="0" skipped="0" tests="29" time="6.939" timestamp="2023-11-22T18:42:51.532660" hostname="80ac3eb7f7f2"><testcase classname="" name="tests.test_cli" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:15: in &lt;module&gt;
    from pandas import Timedelta
E   ModuleNotFoundError: No module named 'pandas'</error></testcase><testcase classname="" name="tests.importance_tests.test_init" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/importance_tests/test_init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/importance_tests/test_init.py:24: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.integration_tests.test_chainermn" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/integration_tests/test_chainermn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration_tests/test_chainermn.py:24: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.integration_tests.test_pytorch_distributed" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/integration_tests/test_pytorch_distributed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration_tests/test_pytorch_distributed.py:11: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.integration_tests.test_pytorch_lightning" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/integration_tests/test_pytorch_lightning.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration_tests/test_pytorch_lightning.py:14: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.integration_tests.test_sklearn" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/integration_tests/test_sklearn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration_tests/test_sklearn.py:6: in &lt;module&gt;
    import scipy as sp
E   ModuleNotFoundError: No module named 'scipy'</error></testcase><testcase classname="" name="tests.multi_objective_tests.test_study" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/multi_objective_tests/test_study.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/multi_objective_tests/test_study.py:10: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.samplers_tests.test_cmaes" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/samplers_tests/test_cmaes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/samplers_tests/test_cmaes.py:19: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.samplers_tests.test_grid" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/samplers_tests/test_grid.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/samplers_tests/test_grid.py:18: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.samplers_tests.search_space_tests.test_group_decomposed" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/samplers_tests/search_space_tests/test_group_decomposed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/samplers_tests/search_space_tests/test_group_decomposed.py:10: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.samplers_tests.search_space_tests.test_intersection" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/samplers_tests/search_space_tests/test_intersection.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/samplers_tests/search_space_tests/test_intersection.py:11: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.samplers_tests.tpe_tests.test_truncnorm" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/samplers_tests/tpe_tests/test_truncnorm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/samplers_tests/tpe_tests/test_truncnorm.py:5: in &lt;module&gt;
    from scipy.stats import truncnorm as truncnorm_scipy
E   ModuleNotFoundError: No module named 'scipy'</error></testcase><testcase classname="" name="tests.storages_tests.test_heartbeat" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/storages_tests/test_heartbeat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/storages_tests/test_heartbeat.py:16: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES_HEARTBEAT
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.storages_tests.test_journal" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/storages_tests/test_journal.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/storages_tests/test_journal.py:14: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.storages_tests.test_storages" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/storages_tests/test_storages.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/storages_tests/test_storages.py:24: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.storages_tests.rdb_tests.test_storage" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/storages_tests/rdb_tests/test_storage.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/storages_tests/rdb_tests/test_storage.py:26: in &lt;module&gt;
    from optuna.testing.storages import StorageSupplier
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.study_tests.test_dataframe" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/study_tests/test_dataframe.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/study_tests/test_dataframe.py:3: in &lt;module&gt;
    import pandas as pd
E   ModuleNotFoundError: No module named 'pandas'</error></testcase><testcase classname="" name="tests.study_tests.test_optimize" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/study_tests/test_optimize.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/study_tests/test_optimize.py:17: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.study_tests.test_study" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/study_tests/test_study.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/study_tests/test_study.py:35: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.trial_tests.test_frozen" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/trial_tests/test_frozen.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/trial_tests/test_frozen.py:14: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.trial_tests.test_trial" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/trial_tests/test_trial.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/trial_tests/test_trial.py:27: in &lt;module&gt;
    from optuna.testing.storages import STORAGE_MODES
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/testing/storages.py:12: in &lt;module&gt;
    import fakeredis
E   ModuleNotFoundError: No module named 'fakeredis'</error></testcase><testcase classname="" name="tests.visualization_tests.test_contour" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_contour.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_contour.py:27: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.test_edf" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "&lt;frozen importlib._bootstrap&gt;", line 1050, in _gcd_import
  File "&lt;frozen importlib._bootstrap&gt;", line 1027, in _find_and_load
  File "&lt;frozen importlib._bootstrap&gt;", line 1006, in _find_and_load_unlocked
  File "&lt;frozen importlib._bootstrap&gt;", line 688, in _load_unlocked
  File "/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/optuna-3.1.1/tests/visualization_tests/test_edf.py", line 36, in &lt;module&gt;
    def save_static_image(figure: Union[go.Figure, Axes, np.ndarray]) -&gt; None:
NameError: name 'go' is not defined</error></testcase><testcase classname="" name="tests.visualization_tests.test_intermediate_plot" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_intermediate_plot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_intermediate_plot.py:14: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.test_parallel_coordinate" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_parallel_coordinate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_parallel_coordinate.py:25: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.test_param_importances" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_param_importances.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_param_importances.py:24: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.test_pareto_front" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_pareto_front.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_pareto_front.py:26: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.test_slice" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/test_slice.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/test_slice.py:19: in &lt;module&gt;
    from optuna.visualization._plotly_imports import go
E   ImportError: cannot import name 'go' from 'optuna.visualization._plotly_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/_plotly_imports.py)</error></testcase><testcase classname="" name="tests.visualization_tests.matplotlib_tests.test_optimization_history" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/optuna-3.1.1/tests/visualization_tests/matplotlib_tests/test_optimization_history.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/visualization_tests/matplotlib_tests/test_optimization_history.py:7: in &lt;module&gt;
    from optuna.visualization.matplotlib._matplotlib_imports import plt
E   ImportError: cannot import name 'plt' from 'optuna.visualization.matplotlib._matplotlib_imports' (/workdir/optuna-3.1.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/optuna/visualization/matplotlib/_matplotlib_imports.py)</error></testcase></testsuite></testsuites>