GLOB sdist-make: /workdir/fire-0.4.0/setup.py
cpythonlibtest-unit-test-tests create: /workdir/fire-0.4.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/fire-0.4.0/.tox/.tmp/package/1/fire-0.4.0.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,fire @ file:///workdir/fire-0.4.0/.tox/.tmp/package/1/fire-0.4.0.zip#sha256=76385dd38c225b1a5d89b34cb82f21e373a493fd6c15fb10f3fdd169532ae458,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,six==1.16.0,termcolor==2.3.0,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2225856883'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/fire/0.4.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/fire-0.4.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/fire-0.4.0
configfile: setup.cfg
collecting ... collected 268 items / 1 error

==================================== ERRORS ====================================
________________ ERROR collecting fire/docstrings_fuzz_test.py _________________
ImportError while importing test module '/workdir/fire-0.4.0/fire/docstrings_fuzz_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
fire/docstrings_fuzz_test.py:24: in <module>
    from hypothesis import example
E   ModuleNotFoundError: No module named 'hypothesis'
=============================== warnings summary ===============================
fire/test_components_py3.py:56
  /workdir/fire-0.4.0/fire/test_components_py3.py:56: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def double(self, count=0):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
-- generated xml file: /workdir/results/fire/0.4.0/1/cpython-test-results.xml --
=========================== short test summary info ============================
ERROR fire/docstrings_fuzz_test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.25s ==========================
ERROR: InvocationError for command /workdir/fire-0.4.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/fire/0.4.0/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
