.package create: /workdir/pytest-mypy-0.10.2/.tox/.package
.package installdeps: setuptools >= 59.6, setuptools-scm[toml] >= 6.4, wheel >= 0.37.1
/workdir/pytest-mypy-0.10.2/.tox/.package/lib/python3.10/site-packages/setuptools_scm/git.py:163: UserWarning: "/workdir/pytest-mypy-0.10.2" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
cpythonlibtest-unit-test-tests create: /workdir/pytest-mypy-0.10.2/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/pytest-mypy-0.10.2/.tox/.tmp/package/1/pytest-mypy-0.10.2.tar.gz
cpythonlibtest-unit-test-tests installed: attrs==23.1.0,exceptiongroup==1.2.0,filelock==3.13.1,iniconfig==2.0.0,mock==5.1.0,mypy==1.7.1,mypy-extensions==1.0.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,pytest-mypy @ file:///workdir/pytest-mypy-0.10.2/.tox/.tmp/package/1/pytest-mypy-0.10.2.tar.gz#sha256=fb3177836f272eb87d18bee6d7fd633148abb464cc818348868f13eca866f2d2,tomli==2.0.1,typing_extensions==4.8.0
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='281520306'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/pytest-mypy/0.10.2/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/pytest-mypy-0.10.2/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/pytest-mypy-0.10.2
configfile: tox.ini
testpaths: tests
plugins: mypy-0.10.2
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_pytest_mypy.py __________________
ImportError while importing test module '/workdir/pytest-mypy-0.10.2/tests/test_pytest_mypy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pytest_mypy.py:6: in <module>
    import pexpect
E   ModuleNotFoundError: No module named 'pexpect'
- generated xml file: /workdir/results/pytest-mypy/0.10.2/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_pytest_mypy.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.08s ===============================
ERROR: InvocationError for command /workdir/pytest-mypy-0.10.2/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/pytest-mypy/0.10.2/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
