GLOB sdist-make: /workdir/fsspec-2022.11.0/setup.py
cpythonlibtest-unit-test-tests create: /workdir/fsspec-2022.11.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/fsspec-2022.11.0/.tox/.tmp/package/1/fsspec-2022.11.0.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,fsspec @ file:///workdir/fsspec-2022.11.0/.tox/.tmp/package/1/fsspec-2022.11.0.zip#sha256=17e62f1548911ca9f41c310cfd786d4a3e011588fca008ae8467cbed0f50db7c,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2759002317'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/fsspec/2022.11.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/fsspec-2022.11.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/fsspec-2022.11.0
collecting ... collected 0 items / 1 skipped

- generated xml file: /workdir/results/fsspec/2022.11.0/1/cpython-test-results.xml -
============================== 1 skipped in 0.11s ==============================
ERROR: InvocationError for command /workdir/fsspec-2022.11.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/fsspec/2022.11.0/1/cpython-test-results.xml (exited with code 5)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
