.package create: /workdir/platformdirs-3.0.0/.tox/.package
.package installdeps: hatch-vcs>=0.3, hatchling>=1.12.2
/workdir/platformdirs-3.0.0/.tox/.package/lib/python3.10/site-packages/setuptools_scm/git.py:163: UserWarning: "/workdir/platformdirs-3.0.0" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
cpythonlibtest-unit-test-tests create: /workdir/platformdirs-3.0.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/platformdirs-3.0.0/.tox/.tmp/package/1/platformdirs-3.0.0.tar.gz
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,platformdirs @ file:///workdir/platformdirs-3.0.0/.tox/.tmp/package/1/platformdirs-3.0.0.tar.gz#sha256=9782133979fadf8a099cb92c317d223f752dacd649a36d6e0a83738b94e25c6a,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='119127638'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/platformdirs/3.0.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/platformdirs-3.0.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/platformdirs-3.0.0
collecting ... collected 183 items / 3 errors

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_android.py ____________________
ImportError while importing test module '/workdir/platformdirs-3.0.0/tests/test_android.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_android.py:9: in <module>
    from pytest_mock import MockerFixture
E   ModuleNotFoundError: No module named 'pytest_mock'
_______________ ERROR collecting tests/test_comp_with_appdirs.py _______________
ImportError while importing test module '/workdir/platformdirs-3.0.0/tests/test_comp_with_appdirs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_comp_with_appdirs.py:7: in <module>
    import appdirs
E   ModuleNotFoundError: No module named 'appdirs'
_____________________ ERROR collecting tests/test_unix.py ______________________
ImportError while importing test module '/workdir/platformdirs-3.0.0/tests/test_unix.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_unix.py:10: in <module>
    from pytest_mock import MockerFixture
E   ModuleNotFoundError: No module named 'pytest_mock'
- generated xml file: /workdir/results/platformdirs/3.0.0/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_android.py
ERROR tests/test_comp_with_appdirs.py
ERROR tests/test_unix.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 0.20s ===============================
ERROR: InvocationError for command /workdir/platformdirs-3.0.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/platformdirs/3.0.0/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
